# Generated by Django 3.1.6 on 2021-03-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('midname', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('startDateOfEmployment', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.PositiveIntegerField()),
                ('officeAssignment', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employmentStatus', models.CharField(max_length=100)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
