# Generated by Django 3.1.6 on 2021-03-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
