# Generated by Django 3.1.6 on 2021-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210315_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
